### ISSUE TITLE
Add plot_by arg to all plots with sequences

### ISSUE THREAD

**Issue by jnumainville** [deephaven/deephaven-plugin-plotly-express#17]
In deephaven's existing plot library, there is the concept of a `plot_by`
A column or list of columns containing factors is passed to `plot_by`, then colors, symbols, etc. are assigned sequentially to each unique value (or group of values) within the column.
This is very useful to assign styling without having to create a column that contains literal colors or other styling.
Additionally, in plotly express, the `color` arg assigns a continuous color scale to numeric columns. This is inconvenient if the numeric columns actually contain classes, such as 1,2,3,4,5. The column would have to have a type conversion applied to be plotted as a factor.

The `plot_by` argument should always assign colors to unique column values, but should only assign symbols, etc. if the corresponding sequence is specified, such as `symbol_discrete_sequence`.

It could also be desirable to have separate arguments, such as `color_by` in case it would be useful to use different sequential styles independently.

`color` (and `color_by`) would override `plot_by`

**Comment by jnumainville** [comment]
Currently, this is (along with `color` and other args) is limited by plugin communication.
Perhaps, while waiting for plugin communication, we could allow specification of extra column categories in some way

**Comment by dsmmcken** [comment]
`plot_by=` should probably just be `by=` for consistency with the deephaven
